const http = require('http');

const postData = JSON.stringify({ document_text: "Industrial Track Sector 7G" });

const options = {
  hostname: 'localhost',
  port: 3000,
  path: '/api/v1/ai/orchestrator',
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(postData)
  }
};

console.log("Starting Multi-Agent Orchestrator Test...");

const req = http.request(options, (res) => {
  res.setEncoding('utf8');
  res.on('data', (chunk) => {
    const lines = chunk.split('\n\n');
    for (const line of lines) {
      if (line.trim().startsWith('data: ')) {
        const data = JSON.parse(line.replace('data: ', ''));
        if (data.status === 'complete') {
          console.log('\n======================================');
          console.log('✅ FINAL DOSSIER GENERATED BY SCRIBE:');
          console.log('======================================\n');
          console.log(data.data.substring(0, 800) + '\n\n... [TRUNCATED FOR BREVITY] ...');
        } else if (data.status === 'error') {
          console.error('\n❌ ERROR:', data.data);
        } else {
          console.log('🤖 AGENT ACTIVE:', data.status);
        }
      }
    }
  });
  
  res.on('end', () => {
    console.log('\nTest complete.');
  });
});

req.on('error', (e) => {
  console.error(`Problem with request: ${e.message}`);
});

req.write(postData);
req.end();
